/* TRAMPA 3 - volumen real: los ~90 anillos de grado que vienen, mas 84
   piezas del resto del catalogo. Sirve para ver si "Ver mas", el filtro
   por piedra y el indice aguantan el tamano definitivo. */
const ORO_ONZA = 4341.30, PLATA_ONZA = 63.46;
const SPOT = { oro24_g: ORO_ONZA/31.1035, plata999_g: PLATA_ONZA/31.1035, fecha:"7 ago 2026" };
const OBRA  = { oro:45, plata:10 };
const EXTRA = { rodio:20, engaste:25 };
const GRADO = [
  {n:"Anillo de Grado 01", tipo:"grado", g:4.7, piedra:"verde", nuevo:true},
  {n:"Anillo de Grado 02", tipo:"grado", g:5.0, piedra:"azul"},
  {n:"Anillo de Grado 03", tipo:"grado", g:3.5, piedra:"morado"},
  {n:"Anillo de Grado 04", tipo:"grado", g:3.6, piedra:"morado"},
  {n:"Anillo de Grado 05", tipo:"grado", g:3.5, piedra:"morado"},
  {n:"Anillo de Grado 06", tipo:"grado", g:4.2, piedra:"azul"},
  {n:"Anillo de Grado 07", tipo:"grado", g:5.2, piedra:"azul"},
  {n:"Anillo de Grado 08", tipo:"grado", g:4.3, piedra:"morado"},
  {n:"Anillo de Grado 09", tipo:"grado", g:5.2, piedra:"blanco"},
  {n:"Anillo de Grado 10", tipo:"grado", g:5.8, piedra:"verde"},
  {n:"Anillo de Grado 11", tipo:"grado", g:6.1, piedra:"morado"},
  {n:"Anillo de Grado 12", tipo:"grado", g:7.6, piedra:"morado", nuevo:true},
  {n:"Anillo de Grado 13", tipo:"grado", g:5.9, piedra:"azul"},
  {n:"Anillo de Grado 14", tipo:"grado", g:7.7, piedra:"azul"},
  {n:"Anillo de Grado 15", tipo:"grado", g:5.8, piedra:"verde"},
  {n:"Anillo de Grado 16", tipo:"grado", g:4.5, piedra:"verde"},
  {n:"Anillo de Grado 17", tipo:"grado", g:5.7, piedra:"morado"},
  {n:"Anillo de Grado 18", tipo:"grado", g:4.6, piedra:"blanco"},
  {n:"Anillo de Grado 19", tipo:"grado", g:6.3, piedra:"azul"},
  {n:"Anillo de Grado 20", tipo:"grado", g:5.9, piedra:"rosa"},
  {n:"Anillo de Grado 21", tipo:"grado", g:4.1, piedra:"azul"},
  {n:"Anillo de Grado 22", tipo:"grado", g:5.7, piedra:"azul"},
  {n:"Anillo de Grado 23", tipo:"grado", g:5.8, piedra:"morado", nuevo:true},
  {n:"Anillo de Grado 24", tipo:"grado", g:4.1, piedra:"rosa"},
  {n:"Anillo de Grado 25", tipo:"grado", g:5.6, piedra:"blanco"},
  {n:"Anillo de Grado 26", tipo:"grado", g:4.6, piedra:"morado"},
  {n:"Anillo de Grado 27", tipo:"grado", g:7.4, piedra:"rojo"},
  {n:"Anillo de Grado 28", tipo:"grado", g:4.6, piedra:"blanco"},
  {n:"Anillo de Grado 29", tipo:"grado", g:4.0, piedra:"blanco"},
  {n:"Anillo de Grado 30", tipo:"grado", g:4.3, piedra:"morado"},
  {n:"Anillo de Grado 31", tipo:"grado", g:4.6, piedra:"amarillo"},
  {n:"Anillo de Grado 32", tipo:"grado", g:7.2, piedra:"rosa"},
  {n:"Anillo de Grado 33", tipo:"grado", g:5.3, piedra:"morado"},
  {n:"Anillo de Grado 34", tipo:"grado", g:7.7, piedra:"azul", nuevo:true},
  {n:"Anillo de Grado 35", tipo:"grado", g:5.6, piedra:"verde"},
  {n:"Anillo de Grado 36", tipo:"grado", g:6.7, piedra:"verde"},
  {n:"Anillo de Grado 37", tipo:"grado", g:7.5, piedra:"amarillo"},
  {n:"Anillo de Grado 38", tipo:"grado", g:3.4, piedra:"rosa"},
  {n:"Anillo de Grado 39", tipo:"grado", g:3.6, piedra:"morado"},
  {n:"Anillo de Grado 40", tipo:"grado", g:5.8, piedra:"blanco"},
  {n:"Anillo de Grado 41", tipo:"grado", g:4.6, piedra:"rosa"},
  {n:"Anillo de Grado 42", tipo:"grado", g:4.8, piedra:"amarillo"},
  {n:"Anillo de Grado 43", tipo:"grado", g:5.9, piedra:"amarillo"},
  {n:"Anillo de Grado 44", tipo:"grado", g:3.5, piedra:"azul"},
  {n:"Anillo de Grado 45", tipo:"grado", g:7.5, piedra:"amarillo", nuevo:true},
  {n:"Anillo de Grado 46", tipo:"grado", g:6.4, piedra:"azul"},
  {n:"Anillo de Grado 47", tipo:"grado", g:3.5, piedra:"rosa"},
  {n:"Anillo de Grado 48", tipo:"grado", g:4.6, piedra:"morado"},
  {n:"Anillo de Grado 49", tipo:"grado", g:7.8, piedra:"blanco"},
  {n:"Anillo de Grado 50", tipo:"grado", g:5.2, piedra:"rosa"},
  {n:"Anillo de Grado 51", tipo:"grado", g:5.0, piedra:"rosa"},
  {n:"Anillo de Grado 52", tipo:"grado", g:4.8, piedra:"amarillo"},
  {n:"Anillo de Grado 53", tipo:"grado", g:4.8, piedra:"morado"},
  {n:"Anillo de Grado 54", tipo:"grado", g:3.7, piedra:"azul"},
  {n:"Anillo de Grado 55", tipo:"grado", g:4.2, piedra:"rojo"},
  {n:"Anillo de Grado 56", tipo:"grado", g:3.8, piedra:"verde", nuevo:true},
  {n:"Anillo de Grado 57", tipo:"grado", g:5.0, piedra:"blanco"},
  {n:"Anillo de Grado 58", tipo:"grado", g:5.5, piedra:"verde"},
  {n:"Anillo de Grado 59", tipo:"grado", g:5.3, piedra:"morado"},
  {n:"Anillo de Grado 60", tipo:"grado", g:4.5, piedra:"verde"},
  {n:"Anillo de Grado 61", tipo:"grado", g:7.0, piedra:"blanco"},
  {n:"Anillo de Grado 62", tipo:"grado", g:5.7, piedra:"rosa"},
  {n:"Anillo de Grado 63", tipo:"grado", g:5.1, piedra:"rojo"},
  {n:"Anillo de Grado 64", tipo:"grado", g:6.3, piedra:"amarillo"},
  {n:"Anillo de Grado 65", tipo:"grado", g:7.6, piedra:"verde"},
  {n:"Anillo de Grado 66", tipo:"grado", g:3.6, piedra:"verde"},
  {n:"Anillo de Grado 67", tipo:"grado", g:4.3, piedra:"verde", nuevo:true},
  {n:"Anillo de Grado 68", tipo:"grado", g:3.3, piedra:"blanco"},
  {n:"Anillo de Grado 69", tipo:"grado", g:5.9, piedra:"rojo"},
  {n:"Anillo de Grado 70", tipo:"grado", g:4.5, piedra:"verde"},
  {n:"Anillo de Grado 71", tipo:"grado", g:5.1, piedra:"rojo"},
  {n:"Anillo de Grado 72", tipo:"grado", g:6.0, piedra:"rojo"},
  {n:"Anillo de Grado 73", tipo:"grado", g:7.6, piedra:"rosa"},
  {n:"Anillo de Grado 74", tipo:"grado", g:7.2, piedra:"morado"},
  {n:"Anillo de Grado 75", tipo:"grado", g:6.2, piedra:"rosa"},
  {n:"Anillo de Grado 76", tipo:"grado", g:3.4, piedra:"blanco"},
  {n:"Anillo de Grado 77", tipo:"grado", g:6.8, piedra:"blanco"},
  {n:"Anillo de Grado 78", tipo:"grado", g:6.3, piedra:"morado", nuevo:true},
  {n:"Anillo de Grado 79", tipo:"grado", g:5.0, piedra:"amarillo"},
  {n:"Anillo de Grado 80", tipo:"grado", g:5.0, piedra:"amarillo"},
  {n:"Anillo de Grado 81", tipo:"grado", g:6.1, piedra:"azul"},
  {n:"Anillo de Grado 82", tipo:"grado", g:4.1, piedra:"verde"},
  {n:"Anillo de Grado 83", tipo:"grado", g:5.2, piedra:"azul"},
  {n:"Anillo de Grado 84", tipo:"grado", g:4.8, piedra:"azul"},
  {n:"Anillo de Grado 85", tipo:"grado", g:3.7, piedra:"morado"},
  {n:"Anillo de Grado 86", tipo:"grado", g:3.9, piedra:"azul"},
  {n:"Anillo de Grado 87", tipo:"grado", g:7.6, piedra:"morado"},
  {n:"Anillo de Grado 88", tipo:"grado", g:3.3, piedra:"blanco"},
  {n:"Anillo de Grado 89", tipo:"grado", g:4.2, piedra:"amarillo", nuevo:true},
  {n:"Anillo de Grado 90", tipo:"grado", g:3.9, piedra:"rojo"}
];
const REGISTRO = {
  "Anillos":[
    {n:"Anillo 01", tipo:"anillo", g:13.5},
    {n:"Anillo 02", tipo:"anillo", g:9.2},
    {n:"Anillo 03", tipo:"anillo", g:7.7},
    {n:"Anillo 04", tipo:"anillo", g:3.4},
    {n:"Anillo 05", tipo:"anillo", g:7.9},
    {n:"Anillo 06", tipo:"anillo", g:13.7},
    {n:"Anillo 07", tipo:"anillo", g:7.8},
    {n:"Anillo 08", tipo:"anillo", g:5.7},
    {n:"Anillo 09", tipo:"anillo", g:3.7},
    {n:"Anillo 10", tipo:"anillo", g:11.0},
    {n:"Anillo 11", tipo:"anillo", g:10.9},
    {n:"Anillo 12", tipo:"anillo", g:7.7},
    {n:"Anillo 13", tipo:"anillo", g:10.3},
    {n:"Anillo 14", tipo:"anillo", g:8.2}
  ],
  "Aros":[
    {n:"Aro 01", tipo:"aro", g:4.5},
    {n:"Aro 02", tipo:"aro", g:13.4},
    {n:"Aro 03", tipo:"aro", g:6.3},
    {n:"Aro 04", tipo:"aro", g:10.3},
    {n:"Aro 05", tipo:"aro", g:13.0},
    {n:"Aro 06", tipo:"aro", g:11.1},
    {n:"Aro 07", tipo:"aro", g:5.6},
    {n:"Aro 08", tipo:"aro", g:9.7},
    {n:"Aro 09", tipo:"aro", g:3.1},
    {n:"Aro 10", tipo:"aro", g:12.1},
    {n:"Aro 11", tipo:"aro", g:8.2},
    {n:"Aro 12", tipo:"aro", g:12.9},
    {n:"Aro 13", tipo:"aro", g:6.3},
    {n:"Aro 14", tipo:"aro", g:4.7}
  ],
  "Cadenas":[
    {n:"Cadena 01", tipo:"cadena", g:8.5},
    {n:"Cadena 02", tipo:"cadena", g:8.0},
    {n:"Cadena 03", tipo:"cadena", g:9.6},
    {n:"Cadena 04", tipo:"cadena", g:9.4},
    {n:"Cadena 05", tipo:"cadena", g:11.5},
    {n:"Cadena 06", tipo:"cadena", g:11.1},
    {n:"Cadena 07", tipo:"cadena", g:4.3},
    {n:"Cadena 08", tipo:"cadena", g:4.9},
    {n:"Cadena 09", tipo:"cadena", g:6.8},
    {n:"Cadena 10", tipo:"cadena", g:11.6},
    {n:"Cadena 11", tipo:"cadena", g:4.4},
    {n:"Cadena 12", tipo:"cadena", g:7.9},
    {n:"Cadena 13", tipo:"cadena", g:10.8},
    {n:"Cadena 14", tipo:"cadena", g:13.9}
  ],
  "Pulseras":[
    {n:"Pulsera 01", tipo:"pulsera", g:11.5},
    {n:"Pulsera 02", tipo:"pulsera", g:7.7},
    {n:"Pulsera 03", tipo:"pulsera", g:4.3},
    {n:"Pulsera 04", tipo:"pulsera", g:9.3},
    {n:"Pulsera 05", tipo:"pulsera", g:6.1},
    {n:"Pulsera 06", tipo:"pulsera", g:11.7},
    {n:"Pulsera 07", tipo:"pulsera", g:10.7},
    {n:"Pulsera 08", tipo:"pulsera", g:6.2},
    {n:"Pulsera 09", tipo:"pulsera", g:13.7},
    {n:"Pulsera 10", tipo:"pulsera", g:3.0},
    {n:"Pulsera 11", tipo:"pulsera", g:3.2},
    {n:"Pulsera 12", tipo:"pulsera", g:7.6},
    {n:"Pulsera 13", tipo:"pulsera", g:6.1},
    {n:"Pulsera 14", tipo:"pulsera", g:7.8}
  ],
  "Zarcillos":[
    {n:"Zarcillo 01", tipo:"zarcillo", g:13.8},
    {n:"Zarcillo 02", tipo:"zarcillo", g:9.3},
    {n:"Zarcillo 03", tipo:"zarcillo", g:2.0},
    {n:"Zarcillo 04", tipo:"zarcillo", g:12.9},
    {n:"Zarcillo 05", tipo:"zarcillo", g:6.1},
    {n:"Zarcillo 06", tipo:"zarcillo", g:9.7},
    {n:"Zarcillo 07", tipo:"zarcillo", g:12.0},
    {n:"Zarcillo 08", tipo:"zarcillo", g:3.4},
    {n:"Zarcillo 09", tipo:"zarcillo", g:6.7},
    {n:"Zarcillo 10", tipo:"zarcillo", g:10.5},
    {n:"Zarcillo 11", tipo:"zarcillo", g:4.4},
    {n:"Zarcillo 12", tipo:"zarcillo", g:12.7},
    {n:"Zarcillo 13", tipo:"zarcillo", g:7.2},
    {n:"Zarcillo 14", tipo:"zarcillo", g:9.6}
  ],
  "Dijes":[
    {n:"Dije 01", tipo:"dije", g:3.0},
    {n:"Dije 02", tipo:"dije", g:13.4},
    {n:"Dije 03", tipo:"dije", g:10.7},
    {n:"Dije 04", tipo:"dije", g:7.6},
    {n:"Dije 05", tipo:"dije", g:10.9},
    {n:"Dije 06", tipo:"dije", g:3.0},
    {n:"Dije 07", tipo:"dije", g:3.9},
    {n:"Dije 08", tipo:"dije", g:13.9},
    {n:"Dije 09", tipo:"dije", g:2.3},
    {n:"Dije 10", tipo:"dije", g:9.1},
    {n:"Dije 11", tipo:"dije", g:7.6},
    {n:"Dije 12", tipo:"dije", g:9.9},
    {n:"Dije 13", tipo:"dije", g:9.3},
    {n:"Dije 14", tipo:"dije", g:9.2}
  ]
};
